### ISSUE TITLE
jaggr exit without any info if receiving small data

### ISSUE THREAD

**Issue by nizsheanez** [rs/jaggr#1]
In Readme you have example of using `vegeta attack -rate 5000` - it works. 
But if i using smaller rate: `vegeta attack -rate 50` then jaggr exiting after couple seconds without any info.

To reproduce: 
```
echo "GET https://blackstarwear.ru/product/p5712-219/" | vegeta attack -rate 50 -duration 1m | vegeta encode | \
jaggr @count=rps \
hist\[100,200,300,400,500\]:code \
p25,p50,p95:latency \
sum:bytes_in \
sum:bytes_out

{"bytes_in":{"sum":0},"bytes_out":{"sum":0},"code":{"hist":{"100":0,"200":0,"300":0,"400":0,"500":0}},"latency":{"p25":0,"p50":0,"p95":0},"rps":0}
{"bytes_in":{"sum":0},"bytes_out":{"sum":0},"code":{"hist":{"100":0,"200":0,"300":0,"400":0,"500":0}},"latency":{"p25":0,"p50":0,"p95":0},"rps":0}
```
It producing only 2 lines of output and exit (it takes ~2 seconds)

Without jaggr `vegeta` producing data 1 minute

**Comment by motoki317** [comment]
Hello, I know this issue is like 6 years old, but in my case the cause was too large input generated by large HTTP responses.

I pushed my patch to my own fork and created a PR #6 if you want to check it out.
