### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by furkand** [rs/jaggr#2]
Hi, I am looking for a solution for a week but I could not found. I was using jaggr + jplot + vegeta on my last MacBook pro-2019 without any problem but when I change my MacBook with m1 It started to return this error I am not sure it is because of the vegeta or not.

```
echo 'GET https://iyifiyat.com/' | \
    vegeta attack -rate 5000 -duration 10m | vegeta encode | \
    jaggr @count=rps \
          hist\[100,200,300,400,500\]:code \
          p25,p50,p95:latency \
          sum:bytes_in \
          sum:bytes_out | \
    jplot rps+code.hist.100+code.hist.200+code.hist.300+code.hist.400+code.hist.500 \
          latency.p95+latency.p50+latency.p25 \
          bytes_in.sum+bytes_out.sum
```    
          
 returns
 
```
 29649 done                echo 'GET https://iyifiyat.com/' |
       29650 broken pipe         vegeta attack -rate 5000 -duration 10m |
       29651 broken pipe         vegeta encode |
       29652 segmentation fault  jaggr @count=rps hist\[100,200,300,400,500\]:code p25,p50,p95:latency   |
       29653 segmentation fault  jplot  latency.p95+latency.p50+latency.p25 bytes_in.sum+bytes_out.sum
```
 
 
 I glad If anyone can help thank you so much

**Comment by gelouko** [comment]
I had the same segmentation fault problems when running `jaggr --version` and `jplot --version`, so I don't think it's related to Vegeta at all!

I've installed jaggr and jplot through brew

**Comment by chandanpasunoori** [comment]
@rs  we can close this issue,  https://github.com/rs/jaggr/pull/3 fixes this, I have verified, I had same problem
